context:
  python_min: 3.11

package:
  name: numpy-typing-compat
  # e.g. '1.22.20250730' for numpy >=1.22,<1.23, numpy-typing-compat version 20250730
  version: ${{ numpy_min }}.${{ ntc_version }}

source:
  - url: https://pypi.org/packages/source/n/numpy-typing-compat/numpy_typing_compat-${{ numpy_min }}.${{ ntc_version }}.tar.gz
    sha256: eb30717dc7390a038c2247be1a7e8bf1a48b8a4701a01960804830a231631bef

build:
  script: ${{ PYTHON }} -m pip install .
  number: 0
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - uv-build
    - pip
  run:
    - python >=${{ python_min }}
    - numpy <${{ numpy_cap }},>=${{ numpy_min }}

tests:
  - python:
      imports:
        - numpy_typing_compat
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/jorenham/numpy-typing-compat
  summary: Static typing compatibility layer for older versions of NumPy
  description: This package provides version-specific boolean constants that allow library authors to write NumPy-version-dependent static type annotations.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lucascolley
    - jorenham
