# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: toml -*-

#                             VVVVVV  minimum `pixi` version
"$schema" = "https://pixi.sh/v0.36.0/schema/manifest/schema.json"

[project]
name = "numpy-typing-compat-feedstock"
version = "3.51.1"  # conda-smithy version used to generate this file
description = "Pixi configuration for conda-forge/numpy-typing-compat-feedstock"
authors = ["@conda-forge/numpy-typing-compat"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[dependencies]
conda-build = ">=24.1"
conda-forge-ci-setup = "4.*"
rattler-build = "*"

[tasks]
[tasks.inspect-all]
cmd = "inspect_artifacts --all-packages"
description = "List contents of all packages found in rattler-build build directory."
[tasks.build]
cmd = "rattler-build build --recipe recipe"
description = "Build numpy-typing-compat-feedstock directly (without setup scripts), no particular variant specified"
[tasks."build-linux_64_numpy_cap1.23numpy_min1.22python_min3.8source_hash6ad36bedd753e90d8fb5c34b635f63bd117b233b2cc95afc045afd2651a0df3c"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap1.23numpy_min1.22python_min3.8source_hash6ad36bedd753e90d8fb5c34b635f63bd117b233b2cc95afc045afd2651a0df3c.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap1.23numpy_min1.22python_min3.8source_hash6ad36bedd753e90d8fb5c34b635f63bd117b233b2cc95afc045afd2651a0df3c directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap1.23numpy_min1.22python_min3.8source_hash6ad36bedd753e90d8fb5c34b635f63bd117b233b2cc95afc045afd2651a0df3c"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap1.23numpy_min1.22python_min3.8source_hash6ad36bedd753e90d8fb5c34b635f63bd117b233b2cc95afc045afd2651a0df3c.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap1.23numpy_min1.22python_min3.8source_hash6ad36bedd753e90d8fb5c34b635f63bd117b233b2cc95afc045afd2651a0df3c"
[tasks."build-linux_64_numpy_cap1.25numpy_min1.23python_min3.8source_hashe2eae3520569ade0c51cea8652565fb80689aca36e4c9aa15a705917ecf805f0"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap1.25numpy_min1.23python_min3.8source_hashe2eae3520569ade0c51cea8652565fb80689aca36e4c9aa15a705917ecf805f0.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap1.25numpy_min1.23python_min3.8source_hashe2eae3520569ade0c51cea8652565fb80689aca36e4c9aa15a705917ecf805f0 directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap1.25numpy_min1.23python_min3.8source_hashe2eae3520569ade0c51cea8652565fb80689aca36e4c9aa15a705917ecf805f0"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap1.25numpy_min1.23python_min3.8source_hashe2eae3520569ade0c51cea8652565fb80689aca36e4c9aa15a705917ecf805f0.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap1.25numpy_min1.23python_min3.8source_hashe2eae3520569ade0c51cea8652565fb80689aca36e4c9aa15a705917ecf805f0"
[tasks."build-linux_64_numpy_cap2.0numpy_min1.25python_min3.9source_hashb470c36d1dfc2acdc323a7ebfc44ac579994b7cbee8b9b2733d3122645a0920f"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap2.0numpy_min1.25python_min3.9source_hashb470c36d1dfc2acdc323a7ebfc44ac579994b7cbee8b9b2733d3122645a0920f.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap2.0numpy_min1.25python_min3.9source_hashb470c36d1dfc2acdc323a7ebfc44ac579994b7cbee8b9b2733d3122645a0920f directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap2.0numpy_min1.25python_min3.9source_hashb470c36d1dfc2acdc323a7ebfc44ac579994b7cbee8b9b2733d3122645a0920f"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap2.0numpy_min1.25python_min3.9source_hashb470c36d1dfc2acdc323a7ebfc44ac579994b7cbee8b9b2733d3122645a0920f.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap2.0numpy_min1.25python_min3.9source_hashb470c36d1dfc2acdc323a7ebfc44ac579994b7cbee8b9b2733d3122645a0920f"
[tasks."build-linux_64_numpy_cap2.1numpy_min2.0python_min3.9source_hash8920e5c72fd6924d328cbce224393a7269265187bf84a217d785aa65a3e98933"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap2.1numpy_min2.0python_min3.9source_hash8920e5c72fd6924d328cbce224393a7269265187bf84a217d785aa65a3e98933.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap2.1numpy_min2.0python_min3.9source_hash8920e5c72fd6924d328cbce224393a7269265187bf84a217d785aa65a3e98933 directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap2.1numpy_min2.0python_min3.9source_hash8920e5c72fd6924d328cbce224393a7269265187bf84a217d785aa65a3e98933"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap2.1numpy_min2.0python_min3.9source_hash8920e5c72fd6924d328cbce224393a7269265187bf84a217d785aa65a3e98933.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap2.1numpy_min2.0python_min3.9source_hash8920e5c72fd6924d328cbce224393a7269265187bf84a217d785aa65a3e98933"
[tasks."build-linux_64_numpy_cap2.2numpy_min2.1python_min3.10source_hashfd9c85b69e5ebc912d617097e34bed5c4deb49a8af7f9f6534c9a5918a40d08f"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap2.2numpy_min2.1python_min3.10source_hashfd9c85b69e5ebc912d617097e34bed5c4deb49a8af7f9f6534c9a5918a40d08f.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap2.2numpy_min2.1python_min3.10source_hashfd9c85b69e5ebc912d617097e34bed5c4deb49a8af7f9f6534c9a5918a40d08f directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap2.2numpy_min2.1python_min3.10source_hashfd9c85b69e5ebc912d617097e34bed5c4deb49a8af7f9f6534c9a5918a40d08f"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap2.2numpy_min2.1python_min3.10source_hashfd9c85b69e5ebc912d617097e34bed5c4deb49a8af7f9f6534c9a5918a40d08f.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap2.2numpy_min2.1python_min3.10source_hashfd9c85b69e5ebc912d617097e34bed5c4deb49a8af7f9f6534c9a5918a40d08f"
[tasks."build-linux_64_numpy_cap2.3numpy_min2.2python_min3.10source_hashe29187c303525274269449ceb8431dfe286b63dd6a00e8a84ba19c98eb3abde7"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap2.3numpy_min2.2python_min3.10source_hashe29187c303525274269449ceb8431dfe286b63dd6a00e8a84ba19c98eb3abde7.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap2.3numpy_min2.2python_min3.10source_hashe29187c303525274269449ceb8431dfe286b63dd6a00e8a84ba19c98eb3abde7 directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap2.3numpy_min2.2python_min3.10source_hashe29187c303525274269449ceb8431dfe286b63dd6a00e8a84ba19c98eb3abde7"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap2.3numpy_min2.2python_min3.10source_hashe29187c303525274269449ceb8431dfe286b63dd6a00e8a84ba19c98eb3abde7.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap2.3numpy_min2.2python_min3.10source_hashe29187c303525274269449ceb8431dfe286b63dd6a00e8a84ba19c98eb3abde7"
[tasks."build-linux_64_numpy_cap2.4numpy_min2.3python_min3.11source_hash5b27cda3b05cf95eacb4296443ff9cd640d5adfed59067d4b7cbcfb22898916d"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap2.4numpy_min2.3python_min3.11source_hash5b27cda3b05cf95eacb4296443ff9cd640d5adfed59067d4b7cbcfb22898916d.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap2.4numpy_min2.3python_min3.11source_hash5b27cda3b05cf95eacb4296443ff9cd640d5adfed59067d4b7cbcfb22898916d directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap2.4numpy_min2.3python_min3.11source_hash5b27cda3b05cf95eacb4296443ff9cd640d5adfed59067d4b7cbcfb22898916d"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap2.4numpy_min2.3python_min3.11source_hash5b27cda3b05cf95eacb4296443ff9cd640d5adfed59067d4b7cbcfb22898916d.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap2.4numpy_min2.3python_min3.11source_hash5b27cda3b05cf95eacb4296443ff9cd640d5adfed59067d4b7cbcfb22898916d"

[feature.smithy.dependencies]
conda-smithy = "*"
[feature.smithy.tasks.build-locally]
cmd = "python ./build-locally.py"
description = "Build packages locally using the same setup scripts used in conda-forge's CI"
[feature.smithy.tasks.smithy]
cmd = "conda-smithy"
description = "Run conda-smithy. Pass necessary arguments."
[feature.smithy.tasks.rerender]
cmd = "conda-smithy rerender"
description = "Rerender the feedstock."
[feature.smithy.tasks.lint]
cmd = "conda-smithy lint --conda-forge recipe"
description = "Lint the feedstock recipe"

[environments]
smithy = ["smithy"]
# This is a copy of default, to be enabled by build_steps.sh during Docker builds
# __PLATFORM_SPECIFIC_ENV__ = []
