# -*- mode: toml -*-
# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
"$schema" = "https://pixi.sh/v0.59.0/schema/manifest/schema.json"

[workspace]
name = "numpy-typing-compat-feedstock"
version = "2026.6.14"  # conda-smithy version used to generate this file
description = "Pixi configuration for conda-forge/numpy-typing-compat-feedstock"
authors = ["@conda-forge/numpy-typing-compat"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]
requires-pixi = ">=0.59.0"

[dependencies]
conda-build = ">=26.3"
conda-forge-ci-setup = "4.*"
rattler-build = "*"

[tasks.inspect-all]
cmd = "inspect_artifacts --all-packages"
description = "List contents of all packages found in rattler-build build directory."
[tasks.build]
cmd = "rattler-build build --recipe recipe"
description = "Build numpy-typing-compat-feedstock directly (without setup scripts), no particular variant specified"
[tasks."build-linux_64_numpy_cap2.1numpy_min2.0numpy_target2.0python_min3.10source_hasheeda5829c77b8aa7be0a9013418019248453aeda33331b46899287d578effdf4"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap2.1numpy_min2.0numpy_target2.0python_min3.10source_hasheeda5829c77b8aa7be0a9013418019248453aeda33331b46899287d578effdf4.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap2.1numpy_min2.0numpy_target2.0python_min3.10source_hasheeda5829c77b8aa7be0a9013418019248453aeda33331b46899287d578effdf4 directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap2.1numpy_min2.0numpy_target2.0python_min3.10source_hasheeda5829c77b8aa7be0a9013418019248453aeda33331b46899287d578effdf4"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap2.1numpy_min2.0numpy_target2.0python_min3.10source_hasheeda5829c77b8aa7be0a9013418019248453aeda33331b46899287d578effdf4.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap2.1numpy_min2.0numpy_target2.0python_min3.10source_hasheeda5829c77b8aa7be0a9013418019248453aeda33331b46899287d578effdf4"
[tasks."build-linux_64_numpy_cap2.2numpy_min2.1numpy_target2.1python_min3.10source_hashffe2859c5c8ad0f2d6e7e6ac14f03ef4eb2c1d77372fae3a6992b7606b6fdcc6"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap2.2numpy_min2.1numpy_target2.1python_min3.10source_hashffe2859c5c8ad0f2d6e7e6ac14f03ef4eb2c1d77372fae3a6992b7606b6fdcc6.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap2.2numpy_min2.1numpy_target2.1python_min3.10source_hashffe2859c5c8ad0f2d6e7e6ac14f03ef4eb2c1d77372fae3a6992b7606b6fdcc6 directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap2.2numpy_min2.1numpy_target2.1python_min3.10source_hashffe2859c5c8ad0f2d6e7e6ac14f03ef4eb2c1d77372fae3a6992b7606b6fdcc6"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap2.2numpy_min2.1numpy_target2.1python_min3.10source_hashffe2859c5c8ad0f2d6e7e6ac14f03ef4eb2c1d77372fae3a6992b7606b6fdcc6.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap2.2numpy_min2.1numpy_target2.1python_min3.10source_hashffe2859c5c8ad0f2d6e7e6ac14f03ef4eb2c1d77372fae3a6992b7606b6fdcc6"
[tasks."build-linux_64_numpy_cap2.3numpy_min2.2numpy_target2.2python_min3.10source_hash0e9818063b3a694e72f872d31af6c180a73bcbfb4efdaf927e3f6b74e09b1701"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap2.3numpy_min2.2numpy_target2.2python_min3.10source_hash0e9818063b3a694e72f872d31af6c180a73bcbfb4efdaf927e3f6b74e09b1701.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap2.3numpy_min2.2numpy_target2.2python_min3.10source_hash0e9818063b3a694e72f872d31af6c180a73bcbfb4efdaf927e3f6b74e09b1701 directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap2.3numpy_min2.2numpy_target2.2python_min3.10source_hash0e9818063b3a694e72f872d31af6c180a73bcbfb4efdaf927e3f6b74e09b1701"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap2.3numpy_min2.2numpy_target2.2python_min3.10source_hash0e9818063b3a694e72f872d31af6c180a73bcbfb4efdaf927e3f6b74e09b1701.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap2.3numpy_min2.2numpy_target2.2python_min3.10source_hash0e9818063b3a694e72f872d31af6c180a73bcbfb4efdaf927e3f6b74e09b1701"
[tasks."build-linux_64_numpy_cap2.4numpy_min2.3numpy_target2.3python_min3.11source_hashf06c8aaca9fa6a9047a7aba5474a7e33870b954544ff276de000dad68c640fbf"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap2.4numpy_min2.3numpy_target2.3python_min3.11source_hashf06c8aaca9fa6a9047a7aba5474a7e33870b954544ff276de000dad68c640fbf.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap2.4numpy_min2.3numpy_target2.3python_min3.11source_hashf06c8aaca9fa6a9047a7aba5474a7e33870b954544ff276de000dad68c640fbf directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap2.4numpy_min2.3numpy_target2.3python_min3.11source_hashf06c8aaca9fa6a9047a7aba5474a7e33870b954544ff276de000dad68c640fbf"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap2.4numpy_min2.3numpy_target2.3python_min3.11source_hashf06c8aaca9fa6a9047a7aba5474a7e33870b954544ff276de000dad68c640fbf.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap2.4numpy_min2.3numpy_target2.3python_min3.11source_hashf06c8aaca9fa6a9047a7aba5474a7e33870b954544ff276de000dad68c640fbf"
[tasks."build-linux_64_numpy_cap2.5numpy_min2.4numpy_target2.4python_min3.11source_hashe4eb661f312a7ad5805677967d5879e04fd7b97627fe910121ce7b1f43aa748c"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap2.5numpy_min2.4numpy_target2.4python_min3.11source_hashe4eb661f312a7ad5805677967d5879e04fd7b97627fe910121ce7b1f43aa748c.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap2.5numpy_min2.4numpy_target2.4python_min3.11source_hashe4eb661f312a7ad5805677967d5879e04fd7b97627fe910121ce7b1f43aa748c directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap2.5numpy_min2.4numpy_target2.4python_min3.11source_hashe4eb661f312a7ad5805677967d5879e04fd7b97627fe910121ce7b1f43aa748c"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap2.5numpy_min2.4numpy_target2.4python_min3.11source_hashe4eb661f312a7ad5805677967d5879e04fd7b97627fe910121ce7b1f43aa748c.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap2.5numpy_min2.4numpy_target2.4python_min3.11source_hashe4eb661f312a7ad5805677967d5879e04fd7b97627fe910121ce7b1f43aa748c"
[tasks."build-linux_64_numpy_cap2.6numpy_min2.5numpy_target2.5python_min3.12source_hash1885a678e9a24564839ed5d1711c0031735fb7de7f0b5ed88d550e5d45a8d4f9"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap2.6numpy_min2.5numpy_target2.5python_min3.12source_hash1885a678e9a24564839ed5d1711c0031735fb7de7f0b5ed88d550e5d45a8d4f9.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap2.6numpy_min2.5numpy_target2.5python_min3.12source_hash1885a678e9a24564839ed5d1711c0031735fb7de7f0b5ed88d550e5d45a8d4f9 directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap2.6numpy_min2.5numpy_target2.5python_min3.12source_hash1885a678e9a24564839ed5d1711c0031735fb7de7f0b5ed88d550e5d45a8d4f9"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap2.6numpy_min2.5numpy_target2.5python_min3.12source_hash1885a678e9a24564839ed5d1711c0031735fb7de7f0b5ed88d550e5d45a8d4f9.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap2.6numpy_min2.5numpy_target2.5python_min3.12source_hash1885a678e9a24564839ed5d1711c0031735fb7de7f0b5ed88d550e5d45a8d4f9"

[feature.smithy.dependencies]
conda-smithy = "*"
[feature.smithy.tasks.build-locally]
cmd = "python ./build-locally.py"
description = "Build packages locally using the same setup scripts used in conda-forge's CI"
[feature.smithy.tasks.smithy]
cmd = "conda-smithy"
description = "Run conda-smithy. Pass necessary arguments."
[feature.smithy.tasks.rerender]
cmd = "conda-smithy rerender"
description = "Rerender the feedstock."
[feature.smithy.tasks.lint]
cmd = "conda-smithy lint --conda-forge recipe"
description = "Lint the feedstock recipe"

[environments]
smithy = ["smithy"]

# This is a copy of default, to be enabled by build_steps.sh during Docker builds
# __PLATFORM_SPECIFIC_ENV__ = []
