# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: toml -*-

#                             VVVVVV  minimum `pixi` version
"$schema" = "https://pixi.sh/v0.36.0/schema/manifest/schema.json"

[project]
name = "numpy-typing-compat-feedstock"
version = "3.51.1"  # conda-smithy version used to generate this file
description = "Pixi configuration for conda-forge/numpy-typing-compat-feedstock"
authors = ["@conda-forge/numpy-typing-compat"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[dependencies]
conda-build = ">=24.1"
conda-forge-ci-setup = "4.*"
rattler-build = "*"

[tasks]
[tasks.inspect-all]
cmd = "inspect_artifacts --all-packages"
description = "List contents of all packages found in rattler-build build directory."
[tasks.build]
cmd = "rattler-build build --recipe recipe"
description = "Build numpy-typing-compat-feedstock directly (without setup scripts), no particular variant specified"
[tasks."build-linux_64_numpy_cap1.23numpy_min1.22"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap1.23numpy_min1.22.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap1.23numpy_min1.22 directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap1.23numpy_min1.22"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap1.23numpy_min1.22.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap1.23numpy_min1.22"
[tasks."build-linux_64_numpy_cap1.25numpy_min1.23"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap1.25numpy_min1.23.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap1.25numpy_min1.23 directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap1.25numpy_min1.23"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap1.25numpy_min1.23.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap1.25numpy_min1.23"
[tasks."build-linux_64_numpy_cap2.0numpy_min1.25"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap2.0numpy_min1.25.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap2.0numpy_min1.25 directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap2.0numpy_min1.25"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap2.0numpy_min1.25.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap2.0numpy_min1.25"
[tasks."build-linux_64_numpy_cap2.1numpy_min2.0"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap2.1numpy_min2.0.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap2.1numpy_min2.0 directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap2.1numpy_min2.0"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap2.1numpy_min2.0.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap2.1numpy_min2.0"
[tasks."build-linux_64_numpy_cap2.2numpy_min2.1"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap2.2numpy_min2.1.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap2.2numpy_min2.1 directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap2.2numpy_min2.1"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap2.2numpy_min2.1.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap2.2numpy_min2.1"
[tasks."build-linux_64_numpy_cap2.3numpy_min2.2"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap2.3numpy_min2.2.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap2.3numpy_min2.2 directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap2.3numpy_min2.2"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap2.3numpy_min2.2.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap2.3numpy_min2.2"
[tasks."build-linux_64_numpy_cap2.4numpy_min2.3"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap2.4numpy_min2.3.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap2.4numpy_min2.3 directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap2.4numpy_min2.3"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap2.4numpy_min2.3.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap2.4numpy_min2.3"

[feature.smithy.dependencies]
conda-smithy = "*"
[feature.smithy.tasks.build-locally]
cmd = "python ./build-locally.py"
description = "Build packages locally using the same setup scripts used in conda-forge's CI"
[feature.smithy.tasks.smithy]
cmd = "conda-smithy"
description = "Run conda-smithy. Pass necessary arguments."
[feature.smithy.tasks.rerender]
cmd = "conda-smithy rerender"
description = "Rerender the feedstock."
[feature.smithy.tasks.lint]
cmd = "conda-smithy lint --conda-forge recipe"
description = "Lint the feedstock recipe"

[environments]
smithy = ["smithy"]
# This is a copy of default, to be enabled by build_steps.sh during Docker builds
# __PLATFORM_SPECIFIC_ENV__ = []
