# -*- mode: toml -*-
# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
"$schema" = "https://pixi.sh/v0.59.0/schema/manifest/schema.json"

[workspace]
name = "numpy-typing-compat-feedstock"
version = "3.53.3"  # conda-smithy version used to generate this file
description = "Pixi configuration for conda-forge/numpy-typing-compat-feedstock"
authors = ["@conda-forge/numpy-typing-compat"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]
requires-pixi = ">=0.59.0"

[dependencies]
conda-build = ">=24.1"
conda-forge-ci-setup = "4.*"
rattler-build = "*"

[tasks.inspect-all]
cmd = "inspect_artifacts --all-packages"
description = "List contents of all packages found in rattler-build build directory."
[tasks.build]
cmd = "rattler-build build --recipe recipe"
description = "Build numpy-typing-compat-feedstock directly (without setup scripts), no particular variant specified"
[tasks."build-linux_64_numpy_cap1.23numpy_min1.22numpy_target1.22python_min3.9source_hash080cadfdc00458ecb50ab467d602f2ae8ee17fbb172c2c651ddfd367976856e7"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap1.23numpy_min1.22numpy_target1.22python_min3.9source_hash080cadfdc00458ecb50ab467d602f2ae8ee17fbb172c2c651ddfd367976856e7.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap1.23numpy_min1.22numpy_target1.22python_min3.9source_hash080cadfdc00458ecb50ab467d602f2ae8ee17fbb172c2c651ddfd367976856e7 directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap1.23numpy_min1.22numpy_target1.22python_min3.9source_hash080cadfdc00458ecb50ab467d602f2ae8ee17fbb172c2c651ddfd367976856e7"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap1.23numpy_min1.22numpy_target1.22python_min3.9source_hash080cadfdc00458ecb50ab467d602f2ae8ee17fbb172c2c651ddfd367976856e7.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap1.23numpy_min1.22numpy_target1.22python_min3.9source_hash080cadfdc00458ecb50ab467d602f2ae8ee17fbb172c2c651ddfd367976856e7"
[tasks."build-linux_64_numpy_cap1.25numpy_min1.23numpy_target1.23python_min3.9source_hash7b16691a05790da0acee02dde957d54d8a7d6d4f3961ddc1bea24cedf2cab470"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap1.25numpy_min1.23numpy_target1.23python_min3.9source_hash7b16691a05790da0acee02dde957d54d8a7d6d4f3961ddc1bea24cedf2cab470.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap1.25numpy_min1.23numpy_target1.23python_min3.9source_hash7b16691a05790da0acee02dde957d54d8a7d6d4f3961ddc1bea24cedf2cab470 directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap1.25numpy_min1.23numpy_target1.23python_min3.9source_hash7b16691a05790da0acee02dde957d54d8a7d6d4f3961ddc1bea24cedf2cab470"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap1.25numpy_min1.23numpy_target1.23python_min3.9source_hash7b16691a05790da0acee02dde957d54d8a7d6d4f3961ddc1bea24cedf2cab470.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap1.25numpy_min1.23numpy_target1.23python_min3.9source_hash7b16691a05790da0acee02dde957d54d8a7d6d4f3961ddc1bea24cedf2cab470"
[tasks."build-linux_64_numpy_cap2.0numpy_min1.25numpy_target1.25python_min3.9source_hash27ff188fe70102312ea5e8553423897a4f3365eee15aa2a7ee1fcf6efc6fed12"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap2.0numpy_min1.25numpy_target1.25python_min3.9source_hash27ff188fe70102312ea5e8553423897a4f3365eee15aa2a7ee1fcf6efc6fed12.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap2.0numpy_min1.25numpy_target1.25python_min3.9source_hash27ff188fe70102312ea5e8553423897a4f3365eee15aa2a7ee1fcf6efc6fed12 directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap2.0numpy_min1.25numpy_target1.25python_min3.9source_hash27ff188fe70102312ea5e8553423897a4f3365eee15aa2a7ee1fcf6efc6fed12"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap2.0numpy_min1.25numpy_target1.25python_min3.9source_hash27ff188fe70102312ea5e8553423897a4f3365eee15aa2a7ee1fcf6efc6fed12.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap2.0numpy_min1.25numpy_target1.25python_min3.9source_hash27ff188fe70102312ea5e8553423897a4f3365eee15aa2a7ee1fcf6efc6fed12"
[tasks."build-linux_64_numpy_cap2.1numpy_min2.0numpy_target2.0python_min3.9source_hash7db9d5e991af03b2ade38f43253e4eb03ab88925230931bff7f559c020676fb1"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap2.1numpy_min2.0numpy_target2.0python_min3.9source_hash7db9d5e991af03b2ade38f43253e4eb03ab88925230931bff7f559c020676fb1.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap2.1numpy_min2.0numpy_target2.0python_min3.9source_hash7db9d5e991af03b2ade38f43253e4eb03ab88925230931bff7f559c020676fb1 directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap2.1numpy_min2.0numpy_target2.0python_min3.9source_hash7db9d5e991af03b2ade38f43253e4eb03ab88925230931bff7f559c020676fb1"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap2.1numpy_min2.0numpy_target2.0python_min3.9source_hash7db9d5e991af03b2ade38f43253e4eb03ab88925230931bff7f559c020676fb1.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap2.1numpy_min2.0numpy_target2.0python_min3.9source_hash7db9d5e991af03b2ade38f43253e4eb03ab88925230931bff7f559c020676fb1"
[tasks."build-linux_64_numpy_cap2.2numpy_min2.1numpy_target2.1python_min3.10source_hash8a868da29e8d076c2aaef8ea9ebb602af917c9752063cfe7c95d6cb60c7b9ea3"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap2.2numpy_min2.1numpy_target2.1python_min3.10source_hash8a868da29e8d076c2aaef8ea9ebb602af917c9752063cfe7c95d6cb60c7b9ea3.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap2.2numpy_min2.1numpy_target2.1python_min3.10source_hash8a868da29e8d076c2aaef8ea9ebb602af917c9752063cfe7c95d6cb60c7b9ea3 directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap2.2numpy_min2.1numpy_target2.1python_min3.10source_hash8a868da29e8d076c2aaef8ea9ebb602af917c9752063cfe7c95d6cb60c7b9ea3"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap2.2numpy_min2.1numpy_target2.1python_min3.10source_hash8a868da29e8d076c2aaef8ea9ebb602af917c9752063cfe7c95d6cb60c7b9ea3.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap2.2numpy_min2.1numpy_target2.1python_min3.10source_hash8a868da29e8d076c2aaef8ea9ebb602af917c9752063cfe7c95d6cb60c7b9ea3"
[tasks."build-linux_64_numpy_cap2.3numpy_min2.2numpy_target2.2python_min3.10source_hash93c9442985ef73dc5a18d29d6bc0f7d47a9afe95372d0a9fc68ca4802ea7ad86"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap2.3numpy_min2.2numpy_target2.2python_min3.10source_hash93c9442985ef73dc5a18d29d6bc0f7d47a9afe95372d0a9fc68ca4802ea7ad86.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap2.3numpy_min2.2numpy_target2.2python_min3.10source_hash93c9442985ef73dc5a18d29d6bc0f7d47a9afe95372d0a9fc68ca4802ea7ad86 directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap2.3numpy_min2.2numpy_target2.2python_min3.10source_hash93c9442985ef73dc5a18d29d6bc0f7d47a9afe95372d0a9fc68ca4802ea7ad86"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap2.3numpy_min2.2numpy_target2.2python_min3.10source_hash93c9442985ef73dc5a18d29d6bc0f7d47a9afe95372d0a9fc68ca4802ea7ad86.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap2.3numpy_min2.2numpy_target2.2python_min3.10source_hash93c9442985ef73dc5a18d29d6bc0f7d47a9afe95372d0a9fc68ca4802ea7ad86"
[tasks."build-linux_64_numpy_cap2.4numpy_min2.3numpy_target2.3python_min3.11source_hash18e00e0f4f2040fe98574890248848c7c6831a975562794da186cf4f3c90b935"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap2.4numpy_min2.3numpy_target2.3python_min3.11source_hash18e00e0f4f2040fe98574890248848c7c6831a975562794da186cf4f3c90b935.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap2.4numpy_min2.3numpy_target2.3python_min3.11source_hash18e00e0f4f2040fe98574890248848c7c6831a975562794da186cf4f3c90b935 directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap2.4numpy_min2.3numpy_target2.3python_min3.11source_hash18e00e0f4f2040fe98574890248848c7c6831a975562794da186cf4f3c90b935"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap2.4numpy_min2.3numpy_target2.3python_min3.11source_hash18e00e0f4f2040fe98574890248848c7c6831a975562794da186cf4f3c90b935.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap2.4numpy_min2.3numpy_target2.3python_min3.11source_hash18e00e0f4f2040fe98574890248848c7c6831a975562794da186cf4f3c90b935"
[tasks."build-linux_64_numpy_cap2.5numpy_min2.4.0rc1numpy_target2.4python_min3.11source_hash59882d23aaff054a2536da80564012cdce33487657be4d79c5925bb8705fcabc"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy_cap2.5numpy_min2.4.0rc1numpy_target2.4python_min3.11source_hash59882d23aaff054a2536da80564012cdce33487657be4d79c5925bb8705fcabc.yaml"
description = "Build numpy-typing-compat-feedstock with variant linux_64_numpy_cap2.5numpy_min2.4.0rc1numpy_target2.4python_min3.11source_hash59882d23aaff054a2536da80564012cdce33487657be4d79c5925bb8705fcabc directly (without setup scripts)"
[tasks."inspect-linux_64_numpy_cap2.5numpy_min2.4.0rc1numpy_target2.4python_min3.11source_hash59882d23aaff054a2536da80564012cdce33487657be4d79c5925bb8705fcabc"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy_cap2.5numpy_min2.4.0rc1numpy_target2.4python_min3.11source_hash59882d23aaff054a2536da80564012cdce33487657be4d79c5925bb8705fcabc.yaml"
description = "List contents of numpy-typing-compat-feedstock packages built for variant linux_64_numpy_cap2.5numpy_min2.4.0rc1numpy_target2.4python_min3.11source_hash59882d23aaff054a2536da80564012cdce33487657be4d79c5925bb8705fcabc"

[feature.smithy.dependencies]
conda-smithy = "*"
[feature.smithy.tasks.build-locally]
cmd = "python ./build-locally.py"
description = "Build packages locally using the same setup scripts used in conda-forge's CI"
[feature.smithy.tasks.smithy]
cmd = "conda-smithy"
description = "Run conda-smithy. Pass necessary arguments."
[feature.smithy.tasks.rerender]
cmd = "conda-smithy rerender"
description = "Rerender the feedstock."
[feature.smithy.tasks.lint]
cmd = "conda-smithy lint --conda-forge recipe"
description = "Lint the feedstock recipe"

[environments]
smithy = ["smithy"]

# This is a copy of default, to be enabled by build_steps.sh during Docker builds
# __PLATFORM_SPECIFIC_ENV__ = []
