# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      ? linux_64_numpy_cap1.23numpy_min1.22python_min3.8source_hash6ad36bedd753e90d8fb5c34b635f63bd117b233b2cc95afc045afd2651a0df3c
      : CONFIG: linux_64_numpy_cap1.23numpy_min1.22python_min3.8source_hash6ad36bedd753e90d8fb5c34b635f63bd117b233b2cc95afc045afd2651a0df3c
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      ? linux_64_numpy_cap1.25numpy_min1.23python_min3.8source_hashe2eae3520569ade0c51cea8652565fb80689aca36e4c9aa15a705917ecf805f0
      : CONFIG: linux_64_numpy_cap1.25numpy_min1.23python_min3.8source_hashe2eae3520569ade0c51cea8652565fb80689aca36e4c9aa15a705917ecf805f0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_numpy_cap2.0numpy_min1.25python_min3.9source_hashb470c36d1dfc2acdc323a7ebfc44ac579994b7cbee8b9b2733d3122645a0920f:
        CONFIG: linux_64_numpy_cap2.0numpy_min1.25python_min3.9source_hashb470c36d1dfc2acdc323a7ebfc44ac579994b7cbee8b9b2733d3122645a0920f
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_numpy_cap2.1numpy_min2.0python_min3.9source_hash8920e5c72fd6924d328cbce224393a7269265187bf84a217d785aa65a3e98933:
        CONFIG: linux_64_numpy_cap2.1numpy_min2.0python_min3.9source_hash8920e5c72fd6924d328cbce224393a7269265187bf84a217d785aa65a3e98933
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_numpy_cap2.2numpy_min2.1python_min3.10source_hashfd9c85b69e5ebc912d617097e34bed5c4deb49a8af7f9f6534c9a5918a40d08f:
        CONFIG: linux_64_numpy_cap2.2numpy_min2.1python_min3.10source_hashfd9c85b69e5ebc912d617097e34bed5c4deb49a8af7f9f6534c9a5918a40d08f
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_numpy_cap2.3numpy_min2.2python_min3.10source_hashe29187c303525274269449ceb8431dfe286b63dd6a00e8a84ba19c98eb3abde7:
        CONFIG: linux_64_numpy_cap2.3numpy_min2.2python_min3.10source_hashe29187c303525274269449ceb8431dfe286b63dd6a00e8a84ba19c98eb3abde7
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_numpy_cap2.4numpy_min2.3python_min3.11source_hash5b27cda3b05cf95eacb4296443ff9cd640d5adfed59067d4b7cbcfb22898916d:
        CONFIG: linux_64_numpy_cap2.4numpy_min2.3python_min3.11source_hash5b27cda3b05cf95eacb4296443ff9cd640d5adfed59067d4b7cbcfb22898916d
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
  timeoutInMinutes: 360
  variables: {}

  steps:
  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export flow_run_id=azure_$(Build.BuildNumber).$(System.JobAttempt)
        export remote_url=$(Build.Repository.Uri)
        export sha=$(Build.SourceVersion)
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
