# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      ? linux_64_numpy_cap1.23numpy_min1.22numpy_target1.22python_min3.9source_hash080cadfdc00458ecb50ab467d602f2ae8ee17fbb172c2c651ddfd367976856e7
      : CONFIG: linux_64_numpy_cap1.23numpy_min1.22numpy_target1.22python_min3.9source_hash080cadfdc00458ecb50ab467d602f2ae8ee17fbb172c2c651ddfd367976856e7
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      ? linux_64_numpy_cap1.25numpy_min1.23numpy_target1.23python_min3.9source_hash7b16691a05790da0acee02dde957d54d8a7d6d4f3961ddc1bea24cedf2cab470
      : CONFIG: linux_64_numpy_cap1.25numpy_min1.23numpy_target1.23python_min3.9source_hash7b16691a05790da0acee02dde957d54d8a7d6d4f3961ddc1bea24cedf2cab470
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      ? linux_64_numpy_cap2.0numpy_min1.25numpy_target1.25python_min3.9source_hash27ff188fe70102312ea5e8553423897a4f3365eee15aa2a7ee1fcf6efc6fed12
      : CONFIG: linux_64_numpy_cap2.0numpy_min1.25numpy_target1.25python_min3.9source_hash27ff188fe70102312ea5e8553423897a4f3365eee15aa2a7ee1fcf6efc6fed12
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      ? linux_64_numpy_cap2.1numpy_min2.0numpy_target2.0python_min3.9source_hash7db9d5e991af03b2ade38f43253e4eb03ab88925230931bff7f559c020676fb1
      : CONFIG: linux_64_numpy_cap2.1numpy_min2.0numpy_target2.0python_min3.9source_hash7db9d5e991af03b2ade38f43253e4eb03ab88925230931bff7f559c020676fb1
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      ? linux_64_numpy_cap2.2numpy_min2.1numpy_target2.1python_min3.10source_hash8a868da29e8d076c2aaef8ea9ebb602af917c9752063cfe7c95d6cb60c7b9ea3
      : CONFIG: linux_64_numpy_cap2.2numpy_min2.1numpy_target2.1python_min3.10source_hash8a868da29e8d076c2aaef8ea9ebb602af917c9752063cfe7c95d6cb60c7b9ea3
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      ? linux_64_numpy_cap2.3numpy_min2.2numpy_target2.2python_min3.10source_hash93c9442985ef73dc5a18d29d6bc0f7d47a9afe95372d0a9fc68ca4802ea7ad86
      : CONFIG: linux_64_numpy_cap2.3numpy_min2.2numpy_target2.2python_min3.10source_hash93c9442985ef73dc5a18d29d6bc0f7d47a9afe95372d0a9fc68ca4802ea7ad86
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      ? linux_64_numpy_cap2.4numpy_min2.3numpy_target2.3python_min3.11source_hash18e00e0f4f2040fe98574890248848c7c6831a975562794da186cf4f3c90b935
      : CONFIG: linux_64_numpy_cap2.4numpy_min2.3numpy_target2.3python_min3.11source_hash18e00e0f4f2040fe98574890248848c7c6831a975562794da186cf4f3c90b935
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      ? linux_64_numpy_cap2.5numpy_min2.4.0rc1numpy_target2.4python_min3.11source_hash59882d23aaff054a2536da80564012cdce33487657be4d79c5925bb8705fcabc
      : CONFIG: linux_64_numpy_cap2.5numpy_min2.4.0rc1numpy_target2.4python_min3.11source_hash59882d23aaff054a2536da80564012cdce33487657be4d79c5925bb8705fcabc
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
  timeoutInMinutes: 360
  variables: {}

  steps:
  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export flow_run_id=azure_$(Build.BuildNumber).$(System.JobAttempt)
        export remote_url=$(Build.Repository.Uri)
        export sha=$(Build.SourceVersion)
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
